//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutSelf
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Hobbies { get; set; }
        public string About { get; set; }
        public virtual Users Users { get; set; }
    }
}
