//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Feedbacks
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string FeedbackText { get; set; }
        public string DateTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
