//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.AboutSelf = new HashSet<AboutSelf>();
            this.Feedbacks = new HashSet<Feedbacks>();
        }
    
        public int Id { get; set; }
        public string Nick { get; set; }
        public string Email { get; set; }
        public virtual ICollection<AboutSelf> AboutSelf { get; set; }
        public virtual ICollection<Feedbacks> Feedbacks { get; set; }
    }
}
